layout: {qmk_keyboard: corne_rotated, qmk_layout: LAYOUT_split_3x6_3}
layers:
  default:
  - ESC
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - '-'
  - TAB
  - {t: A, h: LGUI}
  - {t: S, h: LSHFT}
  - {t: D, h: LCTRL}
  - {t: F, h: LALT}
  - G
  - H
  - {t: J, h: RALT}
  - {t: K, h: RCTRL}
  - {t: L, h: RSHFT}
  - {t: ;, h: RGUI}
  - '&apos_ret'
  - {t: LSHFT, h: sticky, s: '&caps_word'}
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - ','
  - .
  - /
  - \
  - LGUI
  - {t: TAB, h: LSHFT}
  - {t: RET, h: symbol}
  - {t: SPACE, h: nav_fn, s: '&dot_spc'}
  - {t: '&num_dance', h: number}
  - '&smart_mouse'
  nav_fn:
  - F1
  - F2
  - F3
  - F4
  - F5
  - F6
  - PG UP
  - BSPC
  - '&up'
  - DEL
  - Sft+AGr+ F
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - LGUI
  - LSHFT
  - LCTRL
  - LALT
  - {t: ▽, type: trans}
  - PG DN
  - '&left'
  - '&down'
  - '&right'
  - Ctl+ F4
  - BSPC
  - F7
  - F8
  - F9
  - F10
  - F11
  - F12
  - Gui+ TAB
  - Sft+Ctl+ TAB
  - {t: ▽, type: trans}
  - Ctl+ TAB
  - {t: ▽, type: trans}
  - DEL
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  number:
  - '`'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - '&equal_bspc'
  - {t: ▽, type: trans}
  - LGUI
  - LSHFT
  - LCTRL
  - LALT
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - BSPC
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - DEL
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - RET
  - SPACE
  - {t: number, h: toggle, type: held}
  - {t: ▽, type: trans}
  symbol:
  - '~'
  - '!'
  - '@'
  - '#'
  - $
  - '%'
  - ^
  - '&'
  - '*'
  - {t: (, s: '['}
  - {t: ), s: ']'}
  - '&plus_bspc'
  - {t: ▽, type: trans}
  - LGUI
  - LSHFT
  - LCTRL
  - LALT
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: '[', s: '{'}
  - {t: ']', s: '}'}
  - {t: ▽, type: trans}
  - ':'
  - '"'
  - PSCRN
  - CMENU
  - Ctl+ X
  - Ctl+ INS
  - Sft+ INS
  - '&caps_word'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - <
  - '>'
  - '?'
  - '|'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: RET, type: held}
  - SPACE
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  system:
  - BT CLR
  - {t: BT, h: '0'}
  - {t: BT, h: '1'}
  - {t: BT, h: '2'}
  - {t: BT, h: '3'}
  - {t: BT, h: '4'}
  - {t: ▽, type: trans}
  - MUTE
  - VOL UP
  - PP
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - RGB BRD
  - RGB BRI
  - RGB HUD
  - RGB HUI
  - RGB SAD
  - RGB SAI
  - {t: ▽, type: trans}
  - PREV
  - VOL DN
  - NEXT
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - RGB TOG
  - RGB EFF
  - OUT TOG
  - OUT BLE
  - ''
  - '&bootloader'
  - '&bootloader'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  mouse:
  - CANCEL
  - {t: ▽, type: trans}
  - '&mkp LCLK'
  - '&win_up'
  - '&mkp RCLK'
  - {t: ▽, type: trans}
  - '&msc SCRL_UP'
  - '&mkp LCLK'
  - '&mmv MOVE_UP'
  - '&mkp RCLK'
  - '&mkp MB5'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&win_left'
  - '&win_down'
  - '&win_right'
  - {t: ▽, type: trans}
  - '&msc SCRL_DOWN'
  - '&mmv MOVE_LEFT'
  - '&mmv MOVE_DOWN'
  - '&mmv MOVE_RIGHT'
  - '&mkp MB4'
  - BSPC
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&msc SCRL_LEFT'
  - {t: ▽, type: trans}
  - '&msc SCRL_RIGHT'
  - {t: ▽, type: trans}
  - DEL
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - RET
  - SPACE
  - {t: ▽, type: trans}
  - CANCEL
