layout: {qmk_keyboard: corne_rotated, qmk_layout: LAYOUT_split_3x6_3}
layers:
  default:
  - ESC
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - '-'
  - TAB
  - {t: A, h: LGUI}
  - {t: S, h: LSHFT}
  - {t: D, h: LCTRL}
  - {t: F, h: LALT}
  - G
  - H
  - {t: J, h: RALT}
  - {t: K, h: RCTRL}
  - {t: L, h: RSHFT}
  - {t: ;, h: RGUI}
  - ''''
  - LSHFT
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - ','
  - .
  - /
  - {t: \, h: RSHFT}
  - {t: function, h: function}
  - {t: TAB, h: LSHFT}
  - {t: RET, h: symbol}
  - {t: SPACE, h: nav}
  - '&smart_mouse'
  - {t: '&num_dance', h: number}
  nav:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - PG UP
  - BSPC
  - '&up'
  - DEL
  - Sft+AGr+ F
  - INS
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - PG DN
  - '&left'
  - '&down'
  - '&right'
  - Ctl+ F4
  - HOME
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - Gui+ TAB
  - Sft+Ctl+ TAB
  - {t: ▽, type: trans}
  - Ctl+ TAB
  - {t: ▽, type: trans}
  - END
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: nav, h: nav}
  number:
  - '`'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - '='
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: number, h: number, type: held}
  symbol:
  - '~'
  - '!'
  - '@'
  - '#'
  - $
  - '%'
  - ^
  - '&'
  - '*'
  - (
  - )
  - +
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - PSCRN
  - CMENU
  - Ctl+ X
  - Ctl+ INS
  - Sft+ INS
  - CLCK
  - '{'
  - '}'
  - '['
  - ']'
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  - ''
  - ''
  - ''
  function:
  - {t: ▽, type: trans}
  - F1
  - F2
  - F3
  - F4
  - F5
  - F6
  - F7
  - F8
  - F9
  - F10
  - F11
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - F12
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: function, h: function, type: held}
  - ''
  - ''
  - ''
  - ''
  - ''
  system:
  - BT CLR
  - {t: BT, h: '0'}
  - {t: BT, h: '1'}
  - {t: BT, h: '2'}
  - {t: BT, h: '3'}
  - {t: BT, h: '4'}
  - {t: ▽, type: trans}
  - MUTE
  - VOL UP
  - PP
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - OUT TOG
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: ▽, type: trans}
  - PREV
  - VOL DN
  - NEXT
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - OUT BLE
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ''
  - ''
  - {type: held}
  - {type: held}
  - ''
  - ''
  mouse:
  - CANCEL
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&win_up'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&msc SCRL_UP'
  - '&mkp LCLK'
  - '&mmv MOVE_UP'
  - '&mkp RCLK'
  - '&mkp MB5'
  - '&bspc'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&win_left'
  - '&win_down'
  - '&win_right'
  - {t: ▽, type: trans}
  - '&msc SCRL_DOWN'
  - '&mmv MOVE_LEFT'
  - '&mmv MOVE_DOWN'
  - '&mmv MOVE_RIGHT'
  - '&mkp MB4'
  - '&del'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&mkp LCLK'
  - '&msc SCRL_LEFT'
  - {t: ▽, type: trans}
  - '&msc SCRL_RIGHT'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
