layout: {qmk_keyboard: corne_rotated, qmk_layout: LAYOUT_split_3x6_3}
layers:
  default:
  - $$mdi:keyboard-esc$$
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - {t: '-', s: _}
  - $$mdi:keyboard-tab$$
  - A
  - {t: S, h: '$$mdi:apple-keyboard-shift$$'}
  - {t: D, h: '$$mdi:apple-keyboard-control$$'}
  - {t: F, h: '$$mdi:apple-keyboard-option$$'}
  - G
  - H
  - {t: J, h: '$$mdi:apple-keyboard-option$$'}
  - {t: K, h: '$$mdi:apple-keyboard-control$$'}
  - {t: L, h: '$$mdi:apple-keyboard-shift$$'}
  - {t: ;, h: '$$mdi:apple-keyboard-command$$', s: ':'}
  - {t: '''', s: '"'}
  - $$mdi:alpha-w-box$$
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - {t: ',', s: <}
  - {t: ., s: '>'}
  - {t: /, s: '?'}
  - {t: \, s: '|'}
  - $$mdi:apple-keyboard-command$$
  - {t: '$$mdi:keyboard-tab$$', h: '$$mdi:apple-keyboard-shift$$'}
  - {t: '$$mdi:keyboard-space$$', h: SYM}
  - {t: '$$material:keyboard_return$$', h: NAV}
  - {t: '$$mdi:gesture-tap-hold$$', s: '$$mdi:alpha-w-box$$'}
  - {t: '$$mdi:gesture-tap-hold$$', s: '$$mdi:mouse$$'}
  navigate:
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - PG UP
  - {t: '$$mdi:backspace$$', type: backspace}
  - $$mdi:arrow-up-bold$$
  - $$mdi:backspace-reverse-outline$$
  - $$mdi:format-section$$
  - {t: '$$mdi:backspace$$', type: backspace}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - PG DN
  - $$mdi:arrow-left-bold$$
  - $$mdi:arrow-down-bold$$
  - $$mdi:arrow-right-bold$$
  - $$material:close$$
  - {t: '$$mdi:keyboard-return$$', type: enter}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - NEXT APP
  - PREV WIN
  - {t: '$$mdi:transfer$$', type: trans}
  - NEXT WIN
  - B CLICK
  - F CLICK
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  number:
  - {t: '`', s: '~'}
  - {t: '1', s: '!'}
  - {t: '2', s: '@'}
  - {t: '3', s: '#'}
  - {t: '4', s: $}
  - {t: '5', s: '%'}
  - {t: '6', s: ^}
  - {t: '7', s: '&'}
  - {t: '8', s: '*'}
  - {t: '9', s: (}
  - {t: '0', s: )}
  - {t: '=', s: '$$mdi:backspace$$'}
  - '~'
  - '!'
  - {t: '@', h: '$$mdi:apple-keyboard-shift$$'}
  - {t: '#', h: '$$mdi:apple-keyboard-control$$'}
  - {t: $, h: '$$mdi:apple-keyboard-option$$'}
  - '%'
  - ^
  - '&'
  - '*'
  - {t: (, s: '['}
  - {t: ), s: ']'}
  - +
  - PSCRN
  - CMENU
  - $$material:content_cut$$"
  - $$material:content_copy$$"
  - $$material:content_paste$$"
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - $$mdi:keyboard-space$$
  - {t: '$$mdi:keyboard-return$$', type: enter}
  - TOG NUM
  - {t: '$$mdi:transfer$$', type: trans}
  symbol:
  - '~'
  - '!'
  - '@'
  - '#'
  - $
  - '%'
  - ^
  - '&'
  - '*'
  - {t: (, s: '['}
  - {t: ), s: ']'}
  - {t: +, s: '$$mdi:backspace$$'}
  - {t: '`', s: '~'}
  - {t: '1', s: '!'}
  - {t: '2', h: '$$mdi:apple-keyboard-shift$$', s: '@'}
  - {t: '3', h: '$$mdi:apple-keyboard-control$$', s: '#'}
  - {t: '4', h: '$$mdi:apple-keyboard-option$$', s: $}
  - {t: '5', s: '%'}
  - {t: '6', s: ^}
  - {t: '7', s: '&'}
  - {t: '8', s: '*'}
  - {t: '9', s: (}
  - {t: '0', s: )}
  - {t: '=', s: +}
  - PSCRN
  - CMENU
  - $$material:content_cut$$"
  - $$material:content_copy$$"
  - $$material:content_paste$$"
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - <
  - '>'
  - '?'
  - '|'
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - $$mdi:keyboard-space$$
  - {t: '$$mdi:keyboard-return$$', type: enter}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  system:
  - $$mdi:bluetooth-off$$
  - {t: '1', s: '$$mdi:bluetooth-connect$$'}
  - {t: '2', s: '$$mdi:bluetooth-connect$$'}
  - {t: '3', s: '$$mdi:bluetooth-connect$$'}
  - {t: '4', s: '$$mdi:bluetooth-connect$$'}
  - {t: '5', s: '$$mdi:bluetooth-connect$$'}
  - {t: '$$mdi:transfer$$', type: trans}
  - $$mdi:volume-off$$
  - $$mdi:volume-high$$
  - $$mdi:play-pause$$
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - RGB BRD
  - RGB BRI
  - RGB HUD
  - RGB HUI
  - RGB SAD
  - RGB SAI
  - {t: '$$mdi:transfer$$', type: trans}
  - $$mdi:skip-previous$$
  - $$mdi:volume-low$$
  - $$mdi:skip-next$$
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:toggle-switch$$', h: '$$mdi:bluetooth$$', s: '$$mdi:usb$$'}
  - OUT BLE
  - {t: '$$mdi:toggle-switch$$', s: '$$mdi:led-strip$$'}
  - RGB EFF
  - {t: '$$mdi:minus-circle-outline$$', type: none}
  - $$mdi:progress-download$$
  - $$mdi:progress-download$$
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  mouse:
  - $$mdi:close-box$$
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:arrow-up$$', h: '$$mdi:mouse-scroll-wheel$$'}
  - $$mdi:mouse-left-click$$
  - $$mdi:mouse-move-up$$
  - $$mdi:mouse-right-click$$
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:backspace$$', type: backspace}
  - F1
  - F2
  - F3
  - F4
  - F5
  - F6
  - {t: '$$mdi:arrow-down$$', h: '$$mdi:mouse-scroll-wheel$$'}
  - L MOVE
  - $$mdi:mouse-move-down$$
  - R MOVE
  - B CLICK
  - {t: '$$mdi:keyboard-return$$', type: enter}
  - F7
  - F8
  - F9
  - F10
  - F11
  - F12
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:arrow-left$$', h: '$$mdi:mouse-scroll-wheel$$'}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:arrow-right$$', h: '$$mdi:mouse-scroll-wheel$$'}
  - B CLICK
  - F CLICK
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - $$mdi:keyboard-space$$
  - {t: '$$mdi:keyboard-return$$', type: enter}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
