layout: {qmk_keyboard: corne_rotated, qmk_layout: LAYOUT_split_3x6_3}
layers:
  default:
  - $$mdi:keyboard-esc$$
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - '-'
  - $$material:keyboard_tab$$
  - A
  - {t: S, h: '$$material:shift$$'}
  - {t: D, h: '$$material:keyboard_control_key$$'}
  - {t: F, h: '$$material:keyboard_option_key$$'}
  - G
  - H
  - {t: J, h: '$$material:keyboard_option_key$$'}
  - {t: K, h: '$$material:keyboard_control_key$$'}
  - {t: L, h: '$$material:shift$$'}
  - {t: ;, h: '$$material:keyboard_command_key$$'}
  - {t: '''', s: '$$material:keyboard_return$$'}
  - $$mdi:alpha-w-box$$
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - ','
  - .
  - /
  - \
  - $$material:keyboard_command_key$$
  - {t: '$$material:keyboard_tab$$', h: '$$material:shift$$'}
  - {t: '$$material:keyboard_return$$', h: SYM}
  - {t: '$$material:space_bar$$', h: NAV}
  - {t: '$$material:123$$', h: NUM}
  - $$material:mouse$$
  navigate:
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - PG UP
  - $$mdi:backspace$$
  - $$material:arrow_upward$$
  - $$mdi:backspace-reverse$$
  - $$mdi:format-section$$
  - $$mdi:backspace$$
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - PG DN
  - $$material:arrow_back$$
  - $$material:arrow_downward$$
  - $$material:arrow_forward$$
  - $$material:close$$
  - $$material:keyboard_return$$
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - NEXT APP
  - PREV WIN
  - {t: '$$mdi:transfer$$', type: trans}
  - NEXT WIN
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  number:
  - '`'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - {t: '9', s: (}
  - {t: '0', s: )}
  - {t: '=', s: '$$mdi:backspace$$'}
  - '~'
  - '!'
  - {t: '@', h: '$$material:shift$$'}
  - {t: '#', h: '$$material:keyboard_control_key$$'}
  - {t: $, h: '$$material:keyboard_option_key$$'}
  - '%'
  - ^
  - '&'
  - '*'
  - {t: (, s: '['}
  - {t: ), s: ']'}
  - +
  - PSCRN
  - CMENU
  - $$material:content_cut$$"
  - $$material:content_copy$$"
  - $$material:content_paste$$"
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - $$material:space_bar$$
  - TOG NUM
  - {t: '$$mdi:transfer$$', type: trans}
  symbol:
  - '~'
  - '!'
  - '@'
  - '#'
  - $
  - '%'
  - ^
  - '&'
  - '*'
  - {t: (, s: '['}
  - {t: ), s: ']'}
  - {t: +, s: '$$mdi:backspace$$'}
  - '`'
  - '1'
  - {t: '2', h: '$$material:shift$$'}
  - {t: '3', h: '$$material:keyboard_control_key$$'}
  - {t: '4', h: '$$material:keyboard_option_key$$'}
  - '5'
  - '6'
  - '7'
  - '8'
  - {t: '9', s: (}
  - {t: '0', s: )}
  - '='
  - PSCRN
  - CMENU
  - $$material:content_cut$$"
  - $$material:content_copy$$"
  - $$material:content_paste$$"
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - <
  - '>'
  - '?'
  - '|'
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - $$material:keyboard_return$$
  - $$material:space_bar$$
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  system:
  - BT CLR
  - {t: BT, h: '0'}
  - {t: BT, h: '1'}
  - {t: BT, h: '2'}
  - {t: BT, h: '3'}
  - {t: BT, h: '4'}
  - {t: '$$mdi:transfer$$', type: trans}
  - $$material:volume_off$$
  - $$material:volume_up$$
  - $$material:pause$$
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - RGB BRD
  - RGB BRI
  - RGB HUD
  - RGB HUI
  - RGB SAD
  - RGB SAI
  - {t: '$$mdi:transfer$$', type: trans}
  - $$material:skip_previous$$
  - $$material:volume_down$$
  - $$material:skip_next$$
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - RGB TOG
  - RGB EFF
  - OUT TOG
  - OUT BLE
  - ''
  - '&bootloader'
  - '&bootloader'
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  mouse:
  - CANCEL
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - U SCROLL
  - L CLICK
  - U MOVE
  - R CLICK
  - F CLICK
  - $$mdi:backspace$$
  - F1
  - F2
  - F3
  - F4
  - F5
  - F6
  - D SCROLL
  - L MOVE
  - D MOVE
  - R MOVE
  - B CLICK
  - $$material:keyboard_return$$
  - F7
  - F8
  - F9
  - F10
  - F11
  - F12
  - {t: '$$mdi:transfer$$', type: trans}
  - L SCROLL
  - {t: '$$mdi:transfer$$', type: trans}
  - R SCROLL
  - {t: '$$mdi:transfer$$', type: trans}
  - $$mdi:backspace-reverse$$
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
  - $$material:keyboard_return$$
  - $$material:space_bar$$
  - {t: '$$mdi:transfer$$', type: trans}
  - {t: '$$mdi:transfer$$', type: trans}
