name: Build ZMK firmware (nix)
on:
  workflow_dispatch:
  push:
    paths:
      - config/**
      - build.yaml

jobs:
  setup-python:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
  build:
    uses: urob/zmk-actions/.github/workflows/build-user-config.yml@v4
    with:
      # Optionally choose the toolchain to use: Zephyr SDK (default) or GNU Arm
      # Embedded ('gnuarmemb'). The latter results in slightly faster builds.
      toolchain: gnuarmemb